### ISSUE TITLE
Zip and unzip packages

### ISSUE THREAD

**Issue by j-coopz** [Qualys/log4jscanlinux#1]
The qualys linux shell script requires the zip and unzip packages installed and fails silently if one isn't there.... and even worse it reports in the log that it was okay.

**Comment by prerana-ambre** [comment]
Added provision in the script when zip/unzip utility isn't present on the system. FYI: In this case, nested jars won't be reported(only 1st level jars would be detected).

**Comment by prerana-ambre** [comment]
Addressed in latest script.
