### ISSUE TITLE
Script fails if folder /usr/local/qualys/cloud-agent is not present

### ISSUE THREAD

**Issue by johnmccash** [Qualys/log4jscanlinux#2]
Script fails if folder /usr/local/qualys/cloud-agent is not present. It should automatically create it if that's the case.

**Comment by prerana-ambre** [comment]
If agent is not installed, script will create a directory named /usr/local/qualys/cloud-agent/ and dump the standard output and error in files within it.

**Comment by prerana-ambre** [comment]
Fixed.
