### ISSUE TITLE
xdev in find causing issues

### ISSUE THREAD

**Issue by kermana** [Qualys/log4jscanlinux#3]
Hi,

First of all thank you for this script! Being in bash it makes it really easy to run on different servers.

On some of the Linux installs that I tried the script on, I noticed the scan was too quick and did not find the expected vulnerable files. Looking at the script, I noticed that you are using "find / -xdev -name "*.jar" -type f " to find files. 

This is problematic on a lot of our servers because the best practice in Linux dictates that at the very least "home" folders should be in a separate partition. In our case we have  "/boot", "/home", "/opt", "/var" ...etc.  on separate partitions which does not get scanned because of this flag.

The script reports success without actually scanning all partitions which can provide a false sense of security. 
Can we please consider removing  "xdev" flag or put some more complex logic to handle separate partitions?

ps: I personally prefer to get false positives vs false negatives just in case.

Thanks!
Ali

**Comment by prerana-ambre** [comment]
Fixed. Added provision in the script to handle this via command line option.
