### ISSUE TITLE
Unreadable one-liner source code

### ISSUE THREAD

**Issue by gitcnd** [Qualys/log4jscanlinux#4]
*** NOBODY SHOULD EVER RUN UNTRUSTED CODE ***

So it's beyond obvious that you should write your code **clearly**, with comments, and make it _readable_ - so everyone using this can see what it is doing in order to trust it.

**Comment by prerana-ambre** [comment]
Indented the script. Adding comments is under progress.

**Comment by prerana-ambre** [comment]
Done.
