### ISSUE TITLE
This will scan entire of ONE file system only

### ISSUE THREAD

**Issue by yupascal** [Qualys/log4jscanlinux#6]
Per readme, "The script will scan the entire filesystem, including archives (and nested JARs) for the Java class..." It would be more accurate to state This script will scan the entire of ONE file system only"
This will give false result for most Linux systems that built with multiple file systems mount under root. "find / -xdev..." This also makes the rest of parameter at command line useless as it is for root only, it wont be nfs wont be cifs etc.
Also why not scan vxfs? I dont see any justification for that. most of important app would be installed on more robustic vxfs

Pls review and fix this...

**Comment by prerana-ambre** [comment]
Fixed. Added provision in the script to handle this via command line option.
