### ISSUE TITLE
Verify jar/zip/unzip availability

### ISSUE THREAD

**Issue by dpomnean** [Qualys/log4jscanlinux#7]
If zip/unzip and jar programs are not found, output log to the user. Neither are found on a server and 'log4j_findings.stderr' gave the output saying it succeeded, which is false, and no output in 'log4j_findings.stdout'.

I recommend trying to do a lookup for the jar, zip and unzip binaries for execution, and if either is not found, output to the log file. Currently it is assuming these are installed and does not provide output to the user if not found.

**Comment by prerana-ambre** [comment]
Fixed. Logging info in log4j_findings.stderr if zip and unzip binaries not found.
